### PR TITLE
Fix content types link

### PR DESCRIPTION
**Pull request by alinnow**

### CODE REVIEW

**Comment by alinnow** [comment]
Deploy preview for *satoshipay-api* ready!

Built with commit 76fb7577f755587002415f7c76d852ac7e61078b

https://deploy-preview-33--satoshipay-api.netlify.com

**Comment by alinnow** [comment]
@erasmus Netlify demo :sparkles:

**Review by erasmus — APPROVED** [review]

**Comment by erasmus** [comment]
@alanpearce Netlify, great! Is there some admin interface that I can access?

**Comment by alinnow** [comment]
Shared on LastPass

**Pull request merged**
