### PR TITLE
Replace Bitcoin terms with Stellar equivalents

### LINKED ISSUE #16: Replace mentions of Bitcoin in documentation
The introductory section of the documentation refers to bitcoins and satoshis. Maybe even other sections. Please check!

More issues:
- the section HTML tags still refers to bitcoins and satoshis

### PR DESCRIPTION
**Pull request by alinnow**
Close #16

### CODE REVIEW

**Review by andywer — CHANGES_REQUESTED** [review]
We should briefly explain what `stroops` are first.
@erasmus Maybe take <https://www.stellar.org/developers/guides/concepts/assets.html#one-stroop-multiple-stroops>?

**Review by TorstenStueber — CHANGES_REQUESTED** [review]
Can you please update the two images on the site? (one with the sun, there should be an amount that is not so ridiculously high and it should have the new color scheme; then the placeholder further down on the page should also have the new color scheme)

**Comment by alinnow** [comment]
@TorstenStueber I updated the images. However, I don't think it should have been part of this PR at all as it's not related to the ledger change.

**Review by TorstenStueber — DISMISSED** [review]

**Comment by TorstenStueber** [comment]
Partially it is because the number on the sun was too high for lumens. But apart from that you are right.

**Review by erasmus — DISMISSED** [review]
content-mask.png is misleading. The Stellar enabled content-item would hopefully never have a price of "5K". Should be "5"

**Comment by alinnow** [comment]
@andywer Are you still blocking this? satoshis were never explained to bitcoin users. Anyhow, with the other update (#16), it's mentioned several times that 1 XLM = 1x10^7 stroops. I think it's a separate issue and not at all related.

**Review by andywer — APPROVED** [review]

**Review by erasmus — COMMENTED** [review]
Looks good

**Pull request merged**
